### ISSUE TITLE
Documentation Links return Page Not Found

### ISSUE THREAD

**Issue by geoffcrego** [simplesamlphp/simplesamlphp.github.io#3]
The links on this page https://simplesamlphp.org/docs/ return the following message Not Found.

**Comment by keith-e-dynatrace** [comment]
I'm seeing the same thing

**Comment by tvdijen** [comment]
Hi @geoffcrego !  The site is being migrated from it's old home to Github _as we speak_.
In the meantime you can find the docs [here](https://github.com/simplesamlphp/simplesamlphp/tree/simplesamlphp-1.19/docs) and [here](https://github.com/simplesamlphp/simplesamlphp/tree/simplesamlphp-1.19/modules/saml/docs)

**Comment by keith-e-dynatrace** [comment]
> Hi @geoffcrego ! The site is being migrated from it's old home to Github _as we speak_. In the meantime you can find the docs [here](https://github.com/simplesamlphp/simplesamlphp/tree/simplesamlphp-1.19/docs)

Awesome, thanks! Keith

**Comment by tvdijen** [comment]
You're welcome!  Just let me know if you can't find what you're looking for and we'll point you to the right file. That goes for anyone who bumps into this issue!

**Comment by thijskh** [comment]
The documentation is back. There are things to improve. Anyone interested can help out by contributing to [the docs repo](https://github.com/simplesamlphp/docs)
