### ISSUE TITLE
Your website isn't deploying?

### ISSUE THREAD

**Issue by lyda** [simplesamlphp/simplesamlphp.github.io#4]
Your site, https://simplesamlphp.org , is not deploying correctly I think? If I go to it I see (with better formatting):

```
                                  404
          There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation
  to learn how to set up GitHub Pages for your repository,
                 organization, or user account.
```

**Comment by tvdijen** [comment]
@surfnet-niels

**Comment by tvdijen** [comment]
Thanks @lyda for reporting this! The website was migrated a couple of days ago and it worked then.. We'll have to figure out whats wrong.. To be sure, I've restarted the last deployment.. Let's see what that does.

**Comment by tvdijen** [comment]
@surfnet-niels Jaime did something in the settings regarding "publishing the domain".. I'm not sure what he did, but things are in working order again..

@lyda Thanks again, you can browse our website again!

**Comment by MarkDBlackwell** [comment]
Currently, I'm still seeing GitHub Pages 404 at the [new site](https://simplesamlphp.org/).

[Down for everyone or just me](https://downforeveryoneorjustme.com/simplesamlphp.org?proto=http) says it's down for everyone.

I notice that your [main repository](https://github.com/simplesamlphp/simplesamlphp/blob/master/README.md)'s continuous integration reports it sees a 404.

Perhaps you should reopen this issue? :)

The [old site](https://simplesamlphp.github.io/) seems valid as a workaround.

**Comment by thijskh** [comment]
It seems to be a Github quirk. I think I've found and fixed the issue now.
